#!/usr/bin/env bash
set -ue

#
# Runfile script
#
# Add commands as test cases below.
#

USAGE="Usage: run (-e | <command>) ..."

PDFOPEN="skimr"
VITAE="$HOME/cloud/Vitae"
CVPATH="$VITAE/jobsearch/materials/cv-monaco.pdf"
HLPATH="$VITAE/jobsearch/materials/cv-highlights.pdf"

CMDHELP=$(
    grep -Eo '^[[:alnum:]\|]+\s*).*' runfile | sed 's/)[# ]*/\\\\/' | column -s '\\' -t
)

if (( $# )); then
    runcmd="$1"
    shift
else
    echo -e "$USAGE\n\n$CMDHELP"
    exit 1
fi


# Add run commands as switch cases below. Do not make edits
# outside of case blocks. Note: Optional args are available
# as "${@}". If used, consider the first line in the block
# as a usage statement.


case "$runcmd" in

edit)
    if [[ -e Session.vim ]]; then
        mvim -S Session.vim
    else
        mvim +Obsession --servername VIM -O cv.tex cv-web.md
    fi
    ;;

pdf)
    xelatex --output-directory=build cv >/dev/null && \
        $PDFOPEN cv.pdf
    ;;

update)
    xelatex --output-directory=build cv >/dev/null && \
        xelatex --output-directory=build cv >/dev/null && \
        cp build/cv.pdf ~/Sites/jdmonaco_com/files/ && \
        cp build/cv.pdf "$CVPATH" && \
        cp cv-web.md ~/Sites/jdmonaco_com-pages/cv/index.md && \
        cd ../publications && run update && \
        open http://jdmonaco.com/cv/
    ;;

highlights)
    xelatex --output-directory=build cv-highlights >/dev/null && \
      xelatex --output-directory=build cv-highlights >/dev/null && \
      cp build/cv-highlights.pdf "$HLPATH"
    ;;

*)
    echo -e "Error: unrecognized command: $runcmd\n$USAGE\n\n$CMDHELP"
    exit 1
    ;;

esac
